apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: command-demo-container
        image: debian
        command: ["printenv"]
      restartPolicy: Never
  backoffLimit: 0